// Shared file classification logic for corpus testing.
// Used by test_corpus.js and analyze_errors.js to classify files consistently.
//
// Classification hierarchy (checked in order):
// 1. 'corrupt'        — merge conflict markers (cheap insurance, zero found as of Feb 2026)
// 2. 'invalid_syntax' — files M2 itself rejects (exact-path manifest with evidence)
// 3. 'auto_generated' — machine-generated data files (valid M2, stays in CODE_ONLY)
// 4. 'doc_heavy'      — valid M2 code wrapping documentation content (Macaulay2Doc/, *-doc.m2)
// 5. 'raw_doc'        — pure SimpleDoc markup, not M2 expression syntax
// 6. 'code'           — normal M2 code
//
// IMPORTANT: doc_heavy (path-based) runs before raw_doc (content-based) because
// Macaulay2Doc files often start with `document { Key => }` which would trigger
// isRawDocFile's content heuristic.
//
// 'raw_doc', 'corrupt', and 'invalid_syntax' are excluded from CODE_VALID metrics.
// 'doc_heavy' and 'auto_generated' are informational only — these files stay in CODE_VALID.
import path from 'path';

// Manifest of auto-generated data file patterns.
// Each entry: { regex, reason }. Additions/removals must be reviewed.
const AUTO_GENERATED = [
  {
    regex: /SchurVeronese\/betti[A-Z]\d+_\d+_\d+\.m2$/,
    reason: 'Serialized Betti tables — auto-generated HashTable data, lines up to 428K chars'
  }
];

export function isAutoGenerated(filePath) {
  return AUTO_GENERATED.some(entry => entry.regex.test(filePath));
}

// Manifest of files M2's *parser* rejects (syntax errors only, NOT runtime errors).
// Policy: only SYNTAX_ERROR from oracle confirms an entry. RUNTIME_ERROR is
// inconclusive because --stop may halt on a runtime error before reaching syntax
// errors deeper in the file. Such entries require manual snippet-level verification.
//
// Each entry: exact path suffix, reason, date verified, evidence from M2.
// Additions are manual-review-only: run `node test/oracle.js --snippet <code>`,
// verify SYNTAX_ERROR on the specific construct, then add with all required fields.
//
// REVALIDATION: Run `node test/revalidate_invalid.js` to check all entries.
// If upstream fixes a file, the script will flag it for removal.
const INVALID_SYNTAX = [
  {
    path: "packages/PrimaryDecomposition/examples.m2",
    reason: "Singular-style // comments between 72-slash dividers — not valid M2 syntax",
    date: "2026-02-19",
    evidence: "M2 --stop: 'error: syntax error at //' on line 2 of divider block"
  },
];

export function isInvalidSyntax(filePath) {
  return INVALID_SYNTAX.some(entry => filePath.endsWith(entry.path));
}

// Schema validation for INVALID_SYNTAX manifest entries.
// Required fields: path, reason, date (YYYY-MM-DD), evidence.
export function validateManifest() {
  const errors = [];
  const dateFormat = /^\d{4}-\d{2}-\d{2}$/;
  for (let i = 0; i < INVALID_SYNTAX.length; i++) {
    const entry = INVALID_SYNTAX[i];
    const label = entry.path || `entry[${i}]`;
    for (const field of ['path', 'reason', 'date', 'evidence']) {
      if (!entry[field]) errors.push(`Missing '${field}' in ${label}`);
    }
    if (entry.date && !dateFormat.test(entry.date)) {
      errors.push(`Invalid date format '${entry.date}' in ${label} (expected YYYY-MM-DD)`);
    }
    if (entry.path && !entry.path.endsWith('.m2')) {
      errors.push(`Path '${entry.path}' does not end with .m2`);
    }
  }
  return errors;
}

// Export manifest for use by revalidation script
export { INVALID_SYNTAX };

// Original raw-doc detection (kept for backward compat).
// Two detection strategies:
// 1. Filename-based: doc.m2 / *-doc.m2 starting with Node/Key (raw SimpleDoc)
// 2. Content-based: files that are purely document{} blocks (e.g. ov_language.m2)
export function isRawDocFile(code, filePath) {
  const basename = path.basename(filePath);
  const firstLines = code.substring(0, 500);
  // Filename-based: doc.m2 / *-doc.m2 with raw Node/Key markup (not wrapped in doc ///)
  const isDocName = basename === 'doc.m2' || basename.endsWith('-doc.m2');
  if (isDocName && /^\s*(Node|Key)\b/m.test(firstLines) && !/\bdoc\s*\/\/\//.test(firstLines)) {
    return true;
  }
  // Content-based: files starting with document{} blocks containing Key => (raw SimpleDoc)
  if (/^\s*document\s*\{/m.test(firstLines) && /Key\s*=>/m.test(firstLines)) {
    return true;
  }
  return false;
}

// Merge conflict marker detection.
// Checks for git conflict markers at line start: <<<<<<<, =======, >>>>>>>
// None found in corpus as of Feb 2026, but detection is cheap insurance.
function hasMergeMarkers(code) {
  return /^<{7}\s/m.test(code) && /^={7}$/m.test(code) && /^>{7}\s/m.test(code);
}

// Estimate fraction of non-blank lines inside document{} blocks.
// Uses balanced-brace heuristic (same caveat as analyze_errors.js:findDocumentBlocks).
function docBlockFraction(code) {
  const lines = code.split('\n');
  const nonBlank = lines.filter(l => l.trim().length > 0).length;
  if (nonBlank === 0) return 0;

  let inDocBlock = 0;
  let depth = 0;
  let inDoc = false;
  for (const line of lines) {
    const trimmed = line.trim();
    if (!inDoc && /^document\s*\{/.test(trimmed)) {
      inDoc = true;
      depth = 0;
    }
    if (inDoc) {
      for (const ch of line) {
        if (ch === '{') depth++;
        else if (ch === '}') depth--;
      }
      if (trimmed.length > 0) inDocBlock++;
      if (depth <= 0) inDoc = false;
    }
  }
  return inDocBlock / nonBlank;
}

// Full file classifier. Returns one of: 'corrupt', 'auto_generated', 'raw_doc', 'doc_heavy', 'code'.
//
// Order matters: path-based doc_heavy checks run BEFORE content-based raw_doc
// detection, because Macaulay2Doc files often start with `document { Key => }`
// which would otherwise trigger isRawDocFile's content check.
export function classifyFile(code, filePath) {
  // 1. Merge conflict markers (checked first — trumps all)
  if (hasMergeMarkers(code)) return 'corrupt';

  // 2. Invalid syntax — files M2 itself rejects
  if (isInvalidSyntax(filePath)) return 'invalid_syntax';

  // 3. Auto-generated data files (valid M2, stays in CODE_ONLY)
  if (isAutoGenerated(filePath)) return 'auto_generated';

  // 3. Doc-heavy: valid M2 code wrapping mostly documentation
  //    a) Macaulay2Doc/ package — 380+ files, all proper M2 code wrapping doc content
  if (filePath.includes('/Macaulay2Doc/')) return 'doc_heavy';
  //    b) *-doc.m2 files with >50% of lines inside document{} blocks
  const basename = path.basename(filePath);
  if (basename.endsWith('-doc.m2') && docBlockFraction(code) > 0.5) return 'doc_heavy';

  // 4. Raw SimpleDoc (content-based, after path checks)
  if (isRawDocFile(code, filePath)) return 'raw_doc';

  // 5. Normal code
  return 'code';
}
