// Full corpus test: parse ALL .m2 files and report error rates
// Reports metrics: ALL files, CODE-ONLY (canonical), and DOC_HEAVY (informational)
import {parser} from '../src/parser.js';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { execSync } from 'child_process';
import { isRawDocFile, classifyFile, isAutoGenerated, isInvalidSyntax } from './doc_detection.js';
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Find all .m2 files recursively
function findFiles(dir, ext, results = []) {
  try {
    const entries = fs.readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name);
      if (entry.isDirectory() && !entry.name.startsWith('.') && entry.name !== 'node_modules') {
        findFiles(fullPath, ext, results);
      } else if (entry.isFile() && entry.name.endsWith(ext)) {
        results.push(fullPath);
      }
    }
  } catch (e) { /* skip unreadable dirs */ }
  return results;
}

// Count nodes and errors in a parse tree
function analyzeTree(code, tree) {
  let totalNodes = 0;
  let errorNodes = 0;
  let errorTexts = [];

  tree.iterate({
    enter: (node) => {
      totalNodes++;
      if (node.type.isError) {
        errorNodes++;
        const text = code.slice(node.from, Math.min(node.to, node.from + 30));
        if (text.trim()) errorTexts.push(text.trim());
      }
    }
  });
  return { totalNodes, errorNodes, errorTexts };
}

// Main
const m2Root = path.resolve(__dirname, '../../../M2/Macaulay2');
const dirs = [
  path.join(m2Root, 'm2'),
  path.join(m2Root, 'tests'),
  path.join(m2Root, 'packages'),
];

// Track counters
let allFiles = 0, allNodes = 0, allErrors = 0;
let codeFiles = 0, codeNodes = 0, codeErrors = 0;
// DOC_HEAVY informational counters (these files stay IN CODE_ONLY)
let docHeavyFiles = 0, docHeavyNodes = 0, docHeavyErrors = 0;
// AUTO_GENERATED informational counters (these files stay IN CODE_ONLY)
let autoGenFiles = 0, autoGenNodes = 0, autoGenErrors = 0;
let skippedDocFiles = 0;
let corruptFiles = 0;
let invalidSyntaxFiles = 0, invalidSyntaxNodes = 0, invalidSyntaxErrors = 0;
let invalidSyntaxDetail = [];
let worstFiles = [];
let errorCounts = {};

const startTime = Date.now();
const jsonMode = process.argv.includes('--json');
const log = jsonMode ? (msg) => process.stderr.write(msg + '\n') : console.log;

for (const dir of dirs) {
  if (!fs.existsSync(dir)) { log('Skipping (not found): ' + dir); continue; }
  const files = findFiles(dir, '.m2');
  log(`Found ${files.length} .m2 files in ${path.basename(dir)}/`);

  for (const file of files) {
    try {
      const code = fs.readFileSync(file, 'utf-8');
      if (code.length > 500000) continue; // skip very large files

      const classification = classifyFile(code, file);

      const tree = parser.parse(code);
      const { totalNodes: nodes, errorNodes: errors, errorTexts } = analyzeTree(code, tree);

      // ALL track (every file)
      allFiles++;
      allNodes += nodes;
      allErrors += errors;

      if (classification === 'corrupt') {
        corruptFiles++;
        continue; // excluded from CODE_ONLY
      }

      if (classification === 'invalid_syntax') {
        invalidSyntaxFiles++;
        invalidSyntaxNodes += nodes;
        invalidSyntaxErrors += errors;
        invalidSyntaxDetail.push({ path: path.relative(m2Root, file), errors });
        continue; // excluded from CODE_ONLY
      }

      if (classification === 'raw_doc') {
        skippedDocFiles++;
        continue; // excluded from CODE_ONLY
      }

      // Track auto-generated separately (informational only, NOT excluded from CODE_ONLY)
      if (classification === 'auto_generated') {
        autoGenFiles++;
        autoGenNodes += nodes;
        autoGenErrors += errors;
      }

      // CODE-ONLY track (includes 'code', 'doc_heavy', AND 'auto_generated' files)
      codeFiles++;
      codeNodes += nodes;
      codeErrors += errors;

      // Track doc-heavy separately (informational only, NOT excluded)
      if (classification === 'doc_heavy') {
        docHeavyFiles++;
        docHeavyNodes += nodes;
        docHeavyErrors += errors;
      }

      const errorRate = nodes > 0 ? (errors / nodes * 100) : 0;
      if (errorRate > 10 && nodes > 20) {
        worstFiles.push({ file: path.relative(m2Root, file), errorRate: errorRate.toFixed(1), nodes, errors });
      }

      // Count common error patterns (code-only)
      for (const text of errorTexts) {
        const key = text.substring(0, 20);
        errorCounts[key] = (errorCounts[key] || 0) + 1;
      }
    } catch (e) { /* skip unreadable files */ }
  }
}

const elapsed = ((Date.now() - startTime) / 1000).toFixed(1);
const allRate = allNodes > 0 ? (allErrors / allNodes * 100) : 0;
const codeRate = codeNodes > 0 ? (codeErrors / codeNodes * 100) : 0;

// Informational: what CODE_ONLY looks like without doc-heavy files
const strictFiles = codeFiles - docHeavyFiles;
const strictNodes = codeNodes - docHeavyNodes;
const strictErrors = codeErrors - docHeavyErrors;
const strictRate = strictNodes > 0 ? (strictErrors / strictNodes * 100) : 0;

// Informational: what CODE_ONLY looks like without auto-generated files
const noAutoGenFiles = codeFiles - autoGenFiles;
const noAutoGenNodes = codeNodes - autoGenNodes;
const noAutoGenErrors = codeErrors - autoGenErrors;
const noAutoGenRate = noAutoGenNodes > 0 ? (noAutoGenErrors / noAutoGenNodes * 100) : 0;

// Canonical metric source: commit hash + date
let commitInfo = '';
try {
  const hash = execSync('git rev-parse --short HEAD', { cwd: __dirname }).toString().trim();
  const date = execSync('git log -1 --format=%ci HEAD', { cwd: __dirname }).toString().trim().split(' ')[0];
  commitInfo = ` (commit ${hash}, ${date})`;
} catch (e) { /* git not available */ }

// CODE_ALL: same as CODE only, for historical comparison (includes invalid_syntax)
const codeAllFiles = codeFiles + invalidSyntaxFiles;
const codeAllNodes = codeNodes + invalidSyntaxNodes;
const codeAllErrors = codeErrors + invalidSyntaxErrors;
const codeAllRate = codeAllNodes > 0 ? (codeAllErrors / codeAllNodes * 100) : 0;

// JSON output mode for machine consumption (nightly.js, gate.fish)
if (process.argv.includes('--json')) {
  const json = {
    codeAll:   { files: codeAllFiles, nodes: codeAllNodes, errors: codeAllErrors, rate: parseFloat(codeAllRate.toFixed(4)) },
    codeValid: { files: codeFiles,    nodes: codeNodes,    errors: codeErrors,    rate: parseFloat(codeRate.toFixed(4)) },
    excluded:  { rawDoc: skippedDocFiles, corrupt: corruptFiles, invalidSyntax: invalidSyntaxFiles },
    invalidSyntaxDetail,
    parseTime: parseFloat(elapsed),
    commit: commitInfo.trim(),
  };
  console.log(JSON.stringify(json));
  process.exit(codeRate < 5 ? 0 : 1);
}

console.log(`\n=== CORPUS TEST RESULTS${commitInfo} ===`);
console.log(`  ALL files:    ${allFiles} files | ${allNodes} nodes | ${allErrors} errors | ${allRate.toFixed(2)}%`);
console.log(`  CODE_ALL:     ${codeAllFiles} files | ${codeAllNodes} nodes | ${codeAllErrors} errors | ${codeAllRate.toFixed(2)}%  (includes invalid_syntax, for history comparison)`);
console.log(`  CODE_VALID:   ${codeFiles} files | ${codeNodes} nodes | ${codeErrors} errors | ${codeRate.toFixed(2)}%`);
console.log(`  Strict code:  ${strictFiles} files | ${strictNodes} nodes | ${strictErrors} errors | ${strictRate.toFixed(2)}%  (informational: CODE_VALID minus ${docHeavyFiles} doc-heavy files)`);
console.log(`  No autogen:   ${noAutoGenFiles} files | ${noAutoGenNodes} nodes | ${noAutoGenErrors} errors | ${noAutoGenRate.toFixed(2)}%  (informational: CODE_VALID minus ${autoGenFiles} auto-generated files)`);
console.log(`  Excluded: ${skippedDocFiles} raw SimpleDoc + ${corruptFiles} corrupt + ${invalidSyntaxFiles} invalid syntax`);
console.log(`  Parse time: ${elapsed}s`);
console.log(`Target: <5% (CODE_VALID)`);
console.log(`Status: ${codeRate < 5 ? 'PASS' : 'NEEDS IMPROVEMENT'}`);

if (worstFiles.length > 0) {
  console.log(`\n=== WORST FILES (>10% error rate, code-only) ===`);
  worstFiles.sort((a, b) => b.errorRate - a.errorRate);
  worstFiles.slice(0, 15).forEach(f => {
    console.log(`  ${f.errorRate}% errors | ${f.errors}/${f.nodes} nodes | ${f.file}`);
  });
}

// Top error patterns (code-only)
const sorted = Object.entries(errorCounts).sort((a, b) => b[1] - a[1]);
if (sorted.length > 0) {
  console.log(`\n=== TOP ERROR PATTERNS (code-only) ===`);
  sorted.slice(0, 15).forEach(([text, count]) => {
    console.log(`  ${count}x | "${text}"`);
  });
}
