#!/bin/bash
echo "=== M2 Syntax Highlighting Final Test ==="
echo ""
echo "IMPROVEMENTS MADE:"
echo "✅ CSS Import added to index.ts"
echo "✅ External propSource highlighting (like Python/JS)"
echo "✅ JupyterLab CSS variables for theming"
echo "✅ Removed inline styleTags configuration"
echo ""
echo "Starting JupyterLab..."
echo ""
echo "TEST INSTRUCTIONS:"
echo "1. Create new notebook with Macaulay2 kernel"
echo "2. Type this test code:"
echo "   if QQ then gb else ideal"
echo "   R = Ring[x,y,z]"
echo "   print(matrix {{1,2},{3,4}})"
echo ""
echo "EXPECTED COLORS:"
echo "- if/then/else: Blue (keywords)"
echo "- QQ/Ring: Teal (types)"
echo "- gb/ideal/print/matrix: Purple (functions)"
echo ""
echo "DEBUGGING:"
echo "- Open DevTools (F12) → Console"
echo "- Look for 'M2 language registered successfully'"
echo "- Inspect elements to see cm-keyword, cm-typeName, cm-function classes"
echo ""

./venv/bin/jupyter lab --port=8888