default_context:
  author_name: "M2 Jupyter Kernel Team"
  author_email: "m2-jupyter@example.com"
  extension_name: "jupyterlab-m2-codemirror"
  package_name: "jupyterlab_m2_codemirror"
  labextension_name: "jupyterlab-m2-codemirror"
  project_short_description: "Macaulay2 syntax highlighting for JupyterLab"
  has_binder: "n"
  has_settings: "n"
  kind: "frontend"
  repository: "https://github.com/m2-jupyter/jupyterlab-m2-codemirror"