// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
const spec_identifier = {__proto__:null,if:6, then:6, else:6, when:6, do:6, while:6, for:6, from:6, to:6, in:6, break:6, continue:6, return:6, try:6, catch:6, throw:6, local:6, global:6, export:6, exportMutable:6, protect:6, private:6, package:6, use:6, and:6, or:6, not:6, xor:6, new:6, method:6, ZZ:10, QQ:10, RR:10, CC:10, Ring:10, Ideal:10, Module:10, Matrix:10, ChainComplex:10, PolynomialRing:10, QuotientRing:10, List:10, Array:10, HashTable:10, String:10, Symbol:10, Boolean:10, Thing:10, Nothing:10, MutableList:10, MutableHashTable:10, gb:14, res:14, ideal:14, matrix:14, ring:14, map:14, ker:14, coker:14, image:14, decompose:14, primaryDecomposition:14, saturate:14, quotient:14, hilbertFunction:14, hilbertPolynomial:14, hilbertSeries:14, betti:14, regularity:14, codim:14, dim:14, degree:14, genus:14, source:14, target:14, transpose:14, det:14, rank:14, trace:14, factor:14, gcd:14, lcm:14, mod:14, divmod:14, toString:14, print:14, error:14, assert:14, time:14, elapsedTime:14, true:18, false:18, null:22}
export const parser = LRParser.deserialize({
  version: 14,
  states: "!^QVQPOOOOQO'#C^'#C^OOQO'#C`'#C`OOQO'#Cb'#CbOOQO'#Cd'#CdOOQO'#Cf'#CfOOQO'#Cr'#CrOOQO'#Cn'#CnQVQPOOOOQO-E6l-E6l",
  stateData: "!W~OeOS~ORPOTQOVROXSOZTO[UO]UO^UO_UO`UOaUOgUO~O^_[]`ag]~",
  goto: "vgPPhPhPhPhPhPPPPPPPlPPPrTUOWQWORXWTVOW",
  nodeNames: "⚠ Program Keyword Keyword Type Type Function Function Boolean Boolean Null Null Number String LineComment BlockComment Operator Delimiter",
  maxTerm: 23,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "*u~RvX^#ipq#iqr$^rs$ist$duv$dvw$dxy&Vyz&Vz{$d{|$d|}&V}!O&[!O!P(Y!P!Q(m!Q![(u![!])W!]!^&V!^!_)`!_!`)k!`!a*R!b!c*^!c!}*d!}#O&V#P#Q&V#Q#R$d#R#S$d#T#o*d#o#p&V#q#r&V#y#z#i$f$g#i#BY#BZ#i$IS$I_#i$I|$JO#i$JT$JU#i$KV$KW#i&FU&FV#i~#nYe~X^#ipq#i#y#z#i$f$g#i#BY#BZ#i$IS$I_#i$I|$JO#i$JT$JU#i$KV$KW#i&FU&FV#i~$aP!_!`$d~$iO`~~$lVOr$irs%Rs#O$i#O#P%W#P;'S$i;'S;=`&P<%lO$i~%WO]~~%ZRO;'S$i;'S;=`%d;=`O$i~%gWOr$irs%Rs#O$i#O#P%W#P;'S$i;'S;=`&P;=`<%l$i<%lO$i~&SP;=`<%l$i~&[Oa~~&aR`~z{&j}!O'q!`!a$d~&mTOz&jz{&|{;'S&j;'S;=`'k<%lO&j~'PVOz&jz{&|{}&j}!O'f!O;'S&j;'S;=`'k<%lO&j~'kO_~~'nP;=`<%l&j~'vS^~OY'qZ;'S'q;'S;=`(S<%lO'q~(VP;=`<%l'q~(_Qa~!O!P$d!Q![(e~(jP[~!Q![(e~(rP`~!P!Q$d~(zQ[~!O!P)Q!Q![(u~)TP!Q![(e~)]Pa~!_!`$d~)eQ`~!^!_$d!_!`$d~)pR`~qr$^!_!`)y!`!a$d~*OP`~!_!`$d~*WQ`~!_!`$d!`!a$d~*aP!b!c$d~*iSg~!Q![*d!c!}*d#R#S*d#T#o*d",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  specialized: [{term: 23, get: (value) => spec_identifier[value] || -1}],
  tokenPrec: 45
})
