// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Keyword = 2,
  Type = 3,
  Function = 4,
  Boolean = 5,
  Null = 6,
  Identifier = 7,
  Number = 8,
  String = 9,
  LineComment = 10,
  BlockComment = 11,
  Operator = 12,
  Delimiter = 13
