// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Keyword = 3,
  Type = 5,
  Function = 7,
  Boolean = 9,
  Null = 11,
  Number = 12,
  String = 13,
  LineComment = 14,
  BlockComment = 15,
  Operator = 16,
  Delimiter = 17
