#!/bin/bash
echo "=== M2 Syntax Highlighting Test ==="
echo ""
echo "✅ CSS Import added to index.ts"
echo "✅ Bright red test color applied to keywords"
echo "✅ Extension rebuilt with CSS"
echo "✅ JupyterLab 4.4.5 confirmed (uses CodeMirror 6)"
echo ""
echo "Starting JupyterLab..."
echo ""
echo "TEST INSTRUCTIONS:"
echo "1. Open browser DevTools (F12)"
echo "2. Go to Network tab → Filter by CSS"
echo "3. Create new notebook with Macaulay2 kernel"
echo "4. Type: if true then print"
echo ""
echo "EXPECTED:"
echo "- 'if' and 'then' should be RED with YELLOW background"
echo "- Network tab should show style/index.css loaded"
echo "- Console should show 'M2 language registered successfully'"
echo ""
echo "If keywords are NOT red/yellow:"
echo "- Inspect the 'if' token in DevTools"
echo "- Check what CSS classes are applied"
echo "- Look for any cm-keyword class"
echo ""

./venv/bin/jupyter lab --port=8888